### PR TITLE
Categorize pull requests with labels

### PR DESCRIPTION
**Pull request by TimonVS**
This PR adds the ability to categorize PRs in release notes by adding a label to a PR and adding a simple mapping to the Release Drafter config like so:

```yml
categories:
  - label: feature
    title: Features
    order: 0
  - label: fix
    title: Bug Fixes
    order: 1
```

Uncategorized pull requests will show up before categorized ones (without a header).

Let me know what you think of this :)

Partially fixes: #35 as there's no ability to hide certain PRs. I think this should be solved in another PR which adds an option called `filter-pull-requests` which accepts a list of labels maybe?

### CODE REVIEW

**Comment by TimonVS** [comment]
@toolmantim Inferring the order makes a lot of sense, don't know why I hadn't thought of that 😅. I processed your feedback. Let me know if the documentation changes are to your liking :)

**Comment by toolmantim** [comment]
This is so good @TimonVS! Sorry it took a few weeks to merge. This will go out in a release soon.

**Comment by tonglil** [comment]
Wouldn't it make more sense to group the uncategorized PRs on the bottom than at the top?

**Comment by johngully** [comment]
I'd like to see a way to catch the uncategorized PRs with a title so that we can order them any way we like. Perhaps if the label is empty?

```
ategories:
  - title: "🚀 Features"
    labels:
      - "feature"
      - "enhancement"
  - title: "🐛 Bug Fixes"
    labels:
      - "bug"
  - title: "🧰 Maintenance"
    labels:
      - "documentation"
      - "misc"
  - title: "🛍️ Other"
    collapse-after: 5
    labels:
      - ""
```

**Pull request merged**
