### PR TITLE
Convert tests to use Nock

### PR DESCRIPTION
**Pull request by TimonVS**
I've been converting tests to use Nock in preparation for #106. Using Nock will improve the trustworthiness of the tests, especially with regards to updating to Probot 9 that deprecated a lot of methods. Previously those methods would be mocked so they wouldn't cause errors in the tests. With Nock we purely mock the API endpoints so the Octokit methods will be called and will fail when deprecated/removed.

### CODE REVIEW

**Comment by toolmantim** [comment]
I always felt deeply uncomfortable with the default recommended approach of mocking out the functions… I'm sorry for all that mess. I endorse switching to Nock 110%!

**Comment by TimonVS** [comment]
No need for sorry :). The application is tested well and I could reuse almost all expectations.

I just finished up converted the remaining tests to use Nock. Let me know what you think!

**Comment by toolmantim** [comment]
Amazing! Now, to figure out why Travis isn’t testing these PRs 🤔

**Comment by toolmantim** [comment]
Well, I can’t see to unstick Travis. So here it goes!

**Pull request merged**
